# Generated by Django 5.2 on 2025-04-10 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='song.mp3', upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
