# Generated by Django 5.2 on 2025-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
