# Generated by Django 5.2 on 2025-06-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limeapp', '0002_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50),
        ),
    ]
